name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    if: ${{ github.repository_owner == 'thunderbird' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install mdbook and extensions
        run: ./docs/install.sh

      - name: Build docs
        run: mdbook build docs --dest-dir=./../book/docs/latest

      - name: Test docs
        run: mdbook test docs

      - name: Clean docs
        run: |
          rm -rf book/docs/latest/assets/draw.io
          rm book/docs/latest/.gitignore
          rm book/docs/latest/install.sh

      - name: Deploy docs to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch the gh-pages branch
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

           # Get the short commit hash
          COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")

          # Keep necessary files and clean `docs/latest/`
          mkdir -p docs/latest  # Ensure the folder exists
          find docs/latest -mindepth 1 -delete  # Delete old files inside docs/latest

          # Copy new docs to gh-pages branch
          cp -r book/docs/latest/* docs/latest/

          # Remove
          rm -rf book

          # Add, commit, and push changes
          git add .
          git commit -m "Deploy docs update from [${COMMIT_HASH}]" || echo "No changes to commit"
          git push --force-with-lease origin gh-pages
