name: Markdown CI

on:
  pull_request:
    paths:
      - '**.md'
      - '.github/workflows/markdown.yml'

permissions:
  contents: read

jobs:
  markdown_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cargo cache
        uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4  # v1.11.0

      - name: Install mdbook and extensions
        run: ./docs/install.sh

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

      - name: Quality - Spotless Markdown Check
        run: ./gradlew spotlessMarkdownCheck

      - name: Test mdbook docs
        run: mdbook test docs
